name: PlaylistOverlay
options:
  bundleIdPrefix: com.alejmed
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

targets:
  PlaylistOverlay:
    type: application
    platform: macOS
    sources:
      - path: PlaylistOverlay
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.alejmed.PlaylistOverlay
        INFOPLIST_FILE: PlaylistOverlay/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: YES
        PRODUCT_NAME: "Playlist Overlay"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
        MACOSX_DEPLOYMENT_TARGET: "13.0"
    entitlements:
      path: PlaylistOverlay/Resources/PlaylistOverlay.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.automation.apple-events: true
